export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.0,
      numReviews: 10,
      countInStock: 10,
    },
    {
      _id: "2",
      name: "Fit Shirt",
      category: "Shirts",
      image: "d1.jpg",
      price: 69.9,
      brand: "Nike",
      rating: 4.8,
      numReviews: 27,
      countInStock: 8,
    },
    {
      _id: "3",
      name: "Best Pant",
      category: "Pants",
      image: "d1.jpg",
      price: 39.9,
      brand: "Nike",
      rating: 4.3,
      numReviews: 35,
      countInStock: 5,
    },
  ],
};
